# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files  # Prevent giant files from being committed
      - id: check-json  # Check json files for parseable syntax
      - id: pretty-format-json
        args: ['--autofix', '--no-ensure-ascii']
      - id: check-merge-conflict  # Check for files that contain merge conflict strings
      - id: check-yaml  # Checks YAML files for parseable syntax
        args: ['--unsafe']
      - id: end-of-file-fixer  # Ensure that a file is either empty, or ends with one newline
      - id: requirements-txt-fixer  # Sort entries in requirements.txt
      - id: trailing-whitespace  # Trim trailing whitespace
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black  # Format Python code
        args: [--line-length=79]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args: [--disallow-untyped-defs, --disallow-untyped-calls, --disallow-incomplete-defs,
               --check-untyped-defs, --no-implicit-optional, --ignore-missing-imports]
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort
        args: [--line-length=79, --profile=black]
